### ISSUE TITLE
Flexbug1 - Minimum content sizing of flex items not honored

### ISSUE THREAD

**Issue by luisrudge** [luisrudge/postcss-flexbugs-fixes#2]
https://github.com/philipwalton/flexbugs/blob/master/README.md#1-minimum-content-sizing-of-flex-items-not-honored

**Comment by luisrudge** [comment]
This can't be fixed with this tool because there's not enough metadata to take action.

##### Bug
```css
.FlexItem {
  background: hsla(0,0%,0%,.1);  
  margin: 1em;
  padding: 1em;
}
```

##### Workaround
```css
.FlexItem {
  flex-shrink: 0; 
  background: hsla(0,0%,0%,.1);  
  margin: 1em;
  padding: 1em;
}
```
