### ISSUE TITLE
Flexbug2 - Column flex items set to align-items:center overflow their container

### ISSUE THREAD

**Issue by luisrudge** [luisrudge/postcss-flexbugs-fixes#3]
https://github.com/philipwalton/flexbugs/blob/master/README.md#2-column-flex-items-set-to-align-itemscenter-overflow-their-container

**Comment by luisrudge** [comment]
This can't be fixed with this tool because there's not enough metadata to take action.

##### Bug
```css
.FlexItem {
  background: hsla(0,0%,0%,.1);
  padding: 1em;
}
```

##### Workaround
```css
.FlexItem {
  box-sizing: border-box; /* 2 */
  max-width: 100%; /* 1 */
  background: hsla(0,0%,0%,.1);
  padding: 1em;
}
```
