### ISSUE TITLE
Docs are incorrect

### ISSUE THREAD

**Issue by stramel** [luisrudge/postcss-flexbugs-fixes#42]
Input

```css
.foo { flex: 1; }
.bar { flex: 1 1; }
.foz { flex: 1 1 0; }
.baz { flex: 1 1 0px; }
```

**No Longer** Outputs

```css
.foo { flex: 1 1 0%; }
.bar { flex: 1 1 0%; }
.foz { flex: 1 1 0%; }
.baz { flex: 1 1 0%; }
```

instead it outputs:

```css
.foo { flex: 1 1; }
.bar { flex: 1 1; }
.foz { flex: 1 1; }
.baz { flex: 1 1; }
```
