### ISSUE TITLE
Flexbug6 - The default flex value has changed

### ISSUE THREAD

**Issue by luisrudge** [luisrudge/postcss-flexbugs-fixes#7]
https://github.com/philipwalton/flexbugs/blob/master/README.md#6-the-default-flex-value-has-changed

**Comment by luisrudge** [comment]
This can't be fixed with this tool because there's not enough metadata to take action.

[bug](http://codepen.io/philipwalton/pen/myOYqW?editors=110)
[workaround](http://codepen.io/philipwalton/pen/azBrLo?editors=110)

**Comment by trisys3** [comment]
What do you mean "there's not enough metadata"? Wouldn't just setting the flex-shrink for every element (plus `::before` & `::after`) to 1 work?

**Comment by luisrudge** [comment]
Bug:
```css
.FlexContainer {
  display: flex;
  height: 100px;
  width: 500px;
}
.FlexItem {
  width: 300px;
}
```

Workaround:
```css
.FlexContainer {
  display: flex;
  height: 100px;
  width: 500px;
  
}
.FlexItem {
  flex-shrink: 1; /* 1 */
  width: 300px;
}
```

Since we can't possibly know which css classes are child of flex containers, we can't fix ths issue. Does that make sense?

**Comment by luisrudge** [comment]
```css
* {
  flex-shrink: 1;
}
*:before,
*:after {
  flex-shrink: 1;
}
```

Is this what you're suggesting?

**Comment by trisys3** [comment]
Yes. Would that cause any problems?

**Comment by trisys3** [comment]
By the way, how did you get syntax highlighting? I wrote my comment on mobile, was that why they didn't get highlighted?

**Comment by luisrudge** [comment]
```css
div {
  color: red;
}
```

![image](https://cloud.githubusercontent.com/assets/941075/21704360/0892018a-d3a0-11e6-91a6-d9889092697d.png)
