### ISSUE TITLE
Flexbug8 - flex-basis doesn't support calc()

### ISSUE THREAD

**Issue by luisrudge** [luisrudge/postcss-flexbugs-fixes#9]
https://github.com/philipwalton/flexbugs/blob/master/README.md#8-flex-basis-doesnt-support-calc

**Comment by kadmil** [comment]
Do you want to have support of calc for 8.2 with variables? And if yes, how can it be done?

Another option here, as I can see, is to flex-basis's value to height property.

**Comment by luisrudge** [comment]
Yeah. That'll be great.

**Comment by kadmil** [comment]
Excuse me, we're going to set flex-basis value to height property and flex-basis: auto?

**Comment by kadmil** [comment]
And another question.

In order to set 'flex-size' property, we need to know flex-direction at first. Can't imagine a way to do this right now, because it's connected with the markup — we need to know flex-container style, and it seems to be impossible to do on css-only level.

What am I missing or overcomplicating?

**Comment by luisrudge** [comment]
Yeah. You're totally correct. We have this problem in bug 7 as well. We can't know if we need to set width or height without knowing flex direction. For now, just use width or height, and when we have the options workflow in place, we can thing on how to solve this.

**Comment by kadmil** [comment]
Oh, it looks like possibly-breaking-markup solution. Just warning maybe?

**Comment by luisrudge** [comment]
Maybe.. But here's the thing: do we want to warn the user even though the user is doing everything correctly? I rather we only fix what we can indeed fix and call it a day.

**Comment by kadmil** [comment]
There's two things. First: setting height (or width) when we don't know flex-direction breaks markup, I think we shouldn't do this. And second thing, user decides to look for postcss warnings explicitly using one of two plugins, one puts errors to console and second — on web page. Even if we throw these warnings, only ones who want use them will ever see them, so it looks like a good idea. Another trouble with warnings is that there are bugs we can't even detect with css-only.

**Comment by luisrudge** [comment]
Well. This makes more sense. But the problem remains. If the user has an OK css declaration, we'll still emit warnings, right?

## Here are some use cases:

### css has the 8.2bug, we emit a warning

```css
.FlexContainer {
  display: flex;
 }
.FlexItem {
  flex: 0 0 calc(100%/3);
}
```

### css is OK, but we'll still emit a warning, since we can't know if the parent is column or row, so we can't know if we should check for width or height

```css
.FlexContainer {
  display: flex;
  flex-direction: column;
 }
.FlexItem {
  flex: 0 0 auto;
  height: calc(100%/3);
}
```

### css is OK, but we'll still emit a warning, since we can't know if the parent is column or row, so we can't know if we should check for width or height

```css
.FlexContainer {
  display: flex;
  flex-direction: row;
 }
.FlexItem {
  flex: 0 0 auto;
  width: calc(100%/3);
}
```

DOes that make sense?
